name: CI/CD for GKE

on:
  push:
    branches:
      - main  # ajuste a branch conforme necessário

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-cats:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-cats:${{ github.sha }}

      - name: Set up kubectl
        uses: google-github-actions/setup-gke@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          cluster_name: gin-prod
          location: us-central1
          
      - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f deployment.yaml -f service.yaml 
