apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-images-cat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-images-cat
  template:
    metadata:
      labels:
        app: api-images-cat
    spec:
      containers:
      - name: api-images-cat
        image: gcr.io/gin-trabalho/api-cats/api-images-cat:v1
        ports:
        - containerPort: 5000
