apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-cats
  template:
    metadata:
      labels:
        app: api-cats
    spec:
      containers:
      - name: api-cats
        image: gcr.io/gin-trabalho/api-cats:v1
        ports:
        - containerPort: 5000
